### ISSUE TITLE
如何仅评估ReAct在数据集上的表现？

### ISSUE THREAD

**Issue by Hans2573** [LeapLabTHU/ExpeL#2]
感谢您的工作，

如果只执行ReAct，是不是就不需要运行train.py ？

简单说就是，我应该如何设置配置文件，命令，就可以用您提供的代码测试react、reflection在benchmark上的表现，

万分感谢！

**Comment by Andrewzh112** [comment]
您好，

非常感谢您的支持。如果想在我们库运行react，可以运行`python train.py run_name=react resume=false testing=false benchmark=alfworld agent.max_reflection_depth=0`，然后logs上即可看到benchamrk表现。

运行reflexion（3次尝试）：`python train.py run_name=reflexion resume=false testing=false benchmark=alfworld agent.max_reflection_depth=3`。

**Comment by Hans2573** [comment]
非常感谢！
